[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
itertools = "0.10.5"
serde_scan = "0.4.1"

[profile.dev.package."*"]
opt-level = 3
